services:
  # Frontend (Interface do Utilizador)
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

  # Backend (API em FastAPI)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}
      - DB_NAME=${MARIADB_DATABASE}
      - DB_HOST=db
    depends_on:
      - db

  # Base de Dados (MariaDB)
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Ferramenta Gráfica para ver a Base de Dados no Browser
  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MARIADB_USER}
      PMA_PASSWORD: ${MARIADB_PASSWORD}
    depends_on:
      - db

# Volume permanente para guardar os votos com segurança
volumes:
  db_data: